[project]
name = "board"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adafruit-circuitpython-ble>=10.1.0",
    "adafruit-circuitpython-bme280>=2.6.30",
    "adafruit-circuitpython-display-text>=3.3.4",
    "adafruit-circuitpython-displayio-ssd1306>=3.0.4",
    "circuitpython-stubs>=10.0.3",
]
